### ISSUE TITLE
Rolling 24 hr volume

### ISSUE THREAD

**Issue by cag** [protofire/omen-subgraph#26]
Right now, 24 hr volume resets every 24 hours since the unix epoch. It would be good to instead have a rolling set of 24 hr volume fields for every hour, so the 24 hr volume measure actually more closely measures the 24 hr volume.

**Comment by pimato** [comment]
as this issue has the highest priority now, we should use the uniswap v2 oracle price for our currently listed tokens in:
https://etherscan.io/address/0x93db90445b76329e9ed96ecd74e76d8fbf2590d8#code
(list id 3: Omen)
