### ISSUE TITLE
Add fulltext search support

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-subgraph#28]
Would this be an adequate solution to this issue? https://github.com/protofire/omen-exchange/issues/666
More info: https://thegraph.com/docs/define-a-subgraph#defining-fulltext-search-fields

**Comment by cag** [comment]
Whoa when did they add that!?

Yeah it might do the trick...

**Comment by cag** [comment]
Related: https://github.com/graphprotocol/graph-node/issues/1804
