### ISSUE TITLE
Copy fields from FPMM to FPMMParticipation

### ISSUE THREAD

**Issue by cag** [protofire/omen-subgraph#30]
That way, can sort/filter by e.g. `creationTimestamp`.

**Comment by pimato** [comment]
would it be possible too add the possiblity to filter myMarkets by collateral, arbitrator,category and market state?
@cag

**Comment by hpmaxi** [comment]
For market state it must include `answerFinalizedTimestamp` and `openingTimestamp`. Also `fee` and `timeout` for validation purposes.

**Comment by cag** [comment]
Unfortunately, fields that change over the lifetime of the FPMM can't be practically copied to the FPMMParticipation entity, so that means the market state is not a directly filterable parameter. Everything else requested here has been lifted though.
