### ISSUE TITLE
Enable filtering and sorting for the DXdao market curation list 

### ISSUE THREAD

**Issue by pimato** [protofire/omen-subgraph#33]
I think the easiest way to do sorting and filtering is to have in fpmm entity a field that expresses if that market belongs to the curation list. This should be replicated in #30 too.

**Comment by cag** [comment]
The main issue is resolvable, but the repliction in #30 is kind of out of reach right now:

> Unfortunately, fields that change over the lifetime of the FPMM can't be practically copied to the FPMMParticipation entity [...]

This includes the new `curatedByDxDao` field being introduced in #35
