### ISSUE TITLE
Merge FpmmLiquidity and FpmmTrade

### ISSUE THREAD

**Issue by liaojikunwork** [protofire/omen-subgraph#77]
![Screen Shot 2020-10-26 at 8 04 31 AM](https://user-images.githubusercontent.com/34900782/97170306-d9e71a00-1761-11eb-8b10-dfe6cbc4176c.png)
![Screen Shot 2020-10-26 at 8 04 39 AM](https://user-images.githubusercontent.com/34900782/97170314-dc497400-1761-11eb-89a6-eb43a8b48905.png)

I think we can merge all fields and add one more field to check if it's FpmmLiquidity or FpmmTrade.

**Comment by davidalbela** [comment]
They come from different FPMM contract events.

**Comment by liaojikunwork** [comment]
https://github.com/protofire/omen-exchange/issues/1194
Mi-Lan needs to sort fpmmLiquidities and fpmmTrades items by creationTimestamp and implement pagination.
Using the following query, 

For example, using the following query, he gets the first 3 liquidities and trades.
But he needs to only 3 items( merge 3 liquidities and trades and totally 6 items, sort by date and get the first 3)

Is there any solution to implement his needs using query, do you think?
It's not a good idea to fetch all liquidities/trades, merge them, sort them and implement pagination.
```
{
  fpmmLiquidities(
    where: {
      fpmm: "0x748a098efb58b8f61961cab15bcc92a3174c221a"
    }
    first:3
    orderBy: creationTimestamp
  ) {
    outcomeTokenAmounts
    type
  }
  fpmmTrades(
    where:{
      fpmm:"0x748a098efb58b8f61961cab15bcc92a3174c221a"
    }
    first:3
    orderBy: creationTimestamp
  ){
    type
    feeAmount
    outcomeTokensTraded
    collateralToken
  }
}
```

**Comment by davidalbela** [comment]
The records are being used by the bots for different approaches.

What about create a common entity? Eg: `FPMMTransaction` with the following attributes: 
```
id: ID!
fpmm: FixedProductMarketMaker!
user: Account!
transactionType: TransactionType!
collateralAmount: BigInt! 
collateralTokenAddress: Bytes!
collateralTokenAmount: BigInt!
creationTimestamp: BigInt!
```

Where `collateralAmount` field is the `sharesMinted`/`sharesBurnt` from a `FPMMFundingAdded`/`FPMMFundingRemoved` event and `investmentAmount`/`returnAmount` from a `FPMMBuy` /`FPMMSell` event.

There is also a `FpmmParticipation` entity being used for buy, sell, and transfer events.

**Comment by davidalbela** [comment]
Could be possible to include the tx hash on it?

**Comment by Mi-Lan** [comment]
@davidalbela it seems that astro514 made those changes https://github.com/protofire/omen-subgraph/issues/80 for tx hash and also for main issue https://github.com/astro514/omen-subgraph/commit/a66cab18d67d89f180ef17b804f0d61788b3cc64

**Comment by pimato** [comment]
this issue was fixed by https://github.com/protofire/omen-subgraph/pull/81
