### ISSUE TITLE
Add CollateralAmountUSD field, FpmmTradeType and Transaction hash

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-subgraph#84]
-add one new field CollateralAmountUSD
-we would need one more field for determining if transaction is Liquidity(add,remove) or Trade(buy,sell) or Both(add,remove,buy and sell)
since there is no way to query mutliple values for the same field via graph 
-add Transaction hash field

**Comment by pimato** [comment]
there is a fix as a PR for the transaction hash: https://github.com/protofire/omen-subgraph/pull/82

**Comment by Mi-Lan** [comment]
in an effort to sort this issue asap i tried solving this issue myself on the brach https://github.com/protofire/omen-subgraph/tree/test/%2380 but couldn't setup test environment locally...but looking at past pr it seems that something similar to what i have done is the solution....

**Comment by astro514** [comment]
@Mi-Lan @pimato I made a PR for this issue. https://github.com/protofire/omen-subgraph/pull/85
